baseURL = 'https://joshuamlee.com'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Josh Lee Creates'
theme = 'hugo-coder'

[pagination]
pagerSize = 6
enableEmoji = true

[services]
# [services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
noClasses = true
guessSyntax = true

[params]
author = "Josh Lee"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Open-source Developer Advocate and cloud native creator"
keywords = "blog,developer,personal"
info = ["Open Source Developer Advocate"]
avatarURL = "images/author.jpg"
dateFormat = "January 2, 2006"
since = 2017
commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = ["css/custom.css"]
customSCSS = []
customJS = []
customRemoteJS = []
renderer.unsafe = true

[params.plausibleAnalytics]
  domain = "joshuamlee.com"
  serverURL = "plausible.io"
[params.pagination]
eventsPerPage = 10

[taxonomies]
tag = "tags"
category = "categories"
talk = "talks"
series = "series"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/joshleecreates/"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 3
url = "https://bsky.app/profile/joshleecreates.bsky.social"

[[params.social]]
name = "Mastodon"
icon = "fa-brands fa-mastodon fa-2x"
weight = 4
url = "https://hachyderm.io/@joshleecreates"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/joshuamlee/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/@joshleecreates"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://joshuamlee.com/index.xml"
rel = "alternate"
type = "application/rss+xml"


[[languages.en.menu.main]]
name = "Talks"
weight = 3
url = "talks/"

[[languages.en.menu.main]]
name = "Videos"
weight = 4
url = "videos/"

[[languages.en.menu.main]]
name = "Events"
weight = 2
url = "events/"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Contact"
weight = 6
url = "contact/"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"
